name: TownyMenu
version: ${project.version}
main: ${main.class}
api-version: 1.13
softdepend:
  - Towny
author: Tolmikarc. Forked by cobrex
libraries:
  - org.openjdk.nashorn:nashorn-core:15.4

commands:
  townmenu:
    description: Open the town level GUI menu
    aliases: tm
    permission-message: "You do not have permission to use this command!"
    default: true
  plotmenu:
    description: Opens the plot level GUI menu
    aliases: plm
    permission-message: "You do not have permission to use this command!"
    default: true
  chunkview:
    description: View the boarders of the chunk you are standing in.
    aliases:
      - cv
      - chunkv
    permission: chunkview.view
    permission-message: "You do not have permission to use this command!"
    default: true
    usage: |-
      /chunkview - to view the chunk boarder.
permissions:
  townmenu.view:
    description: Opens the town level GUI
    default: true
  plotmenu.view:
    description: Opens the plot level GUI
    default: true
  chunkview.view:
    description: Allows use of /chunkview
    default: true